<a href="https://colab.research.google.com/github/yahyasungur/nlp_dl_ml_projects/blob/master/Data_Analysis_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1) NumPy Arrays

In [1]:
# 1D array
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array(my_list)

In [7]:
# 2D array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Using built-in methods

In [10]:
# arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# ones
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# linspace
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
# eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# arrays of random numbers (uniform distribution between 0-1)
np.random.rand(5)

array([0.93572894, 0.66164897, 0.64012742, 0.64411734, 0.50593683])

In [21]:
np.random.rand(4,4)

array([[0.6211203 , 0.72245597, 0.6969668 , 0.88352465],
       [0.29106978, 0.63665818, 0.28612122, 0.8783836 ],
       [0.11687382, 0.0663619 , 0.43155583, 0.39593336],
       [0.56506504, 0.71140353, 0.58791038, 0.16816482]])

In [22]:
# Std normal distribution (Gaussian dist.)
np.random.randn(4)

array([-0.61847748, -1.07330212, -2.30555448, -0.18835594])

In [23]:
np.random.randn(4,5)

array([[ 0.42836592,  0.10147937,  0.22867037,  0.98237432, -0.65944102],
       [ 0.87503601, -0.23389966,  2.33437603,  0.02299739, -1.04871282],
       [-0.04389318,  0.05704897, -1.08439024, -0.09321062,  0.02914186],
       [ 0.26039961, -0.36736728,  0.13820031, -0.38247262,  0.12685269]])

In [30]:
# randint
np.random.randint(0,100)

37

In [31]:
np.random.randint(0,100,10)

array([39, 44, 82, 20, 58, 62, 46, 47, 92, 45])

## Useful attributes and methods

In [32]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
# reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# max - min
ran_arr = np.random.randint(0,50,10)

In [36]:
ran_arr

array([34, 28, 35,  3,  2,  8, 10, 20, 22, 26])

In [37]:
ran_arr.max() , ran_arr.min()

(35, 2)

In [39]:
ran_arr.argmax() , ran_arr.argmin() #position of max - min

(2, 4)

In [40]:
# shape
arr.shapearr = np.arange(10,21)

(25,)

In [41]:
b = arr.reshape(5,5)

In [42]:
b.shape

(5, 5)

In [43]:
# dtype
arr.dtype

dtype('int64')

#2) NumPy Indexing and Selection

In [45]:
arr = np.arange(10,21)

In [46]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
arr[5]

15

In [48]:
arr[:4] = 100

In [49]:
arr

array([100, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [50]:
arr = np.arange(10,21)

In [51]:
slice_arr = arr[0:6]

In [52]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [53]:
slice_arr[:] = 99

In [54]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [56]:
arr_cp = arr.copy()

In [57]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [58]:
arr[:] = 100

In [59]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [61]:
arr = np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [64]:
b = arr > 5

In [66]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr < 3]

array([0, 1, 2])